{"name": "test_user_auth_invalid_data", "status": "passed", "steps": [{"name": "Отправляем запрос на аторизацию с неправильными данными", "status": "passed", "start": 1665056627120, "stop": 1665056627120}, {"name": "Проверяем что указанные данные не верны и статус код = 401", "status": "passed", "start": 1665056627120, "stop": 1665056627120}], "start": 1665056627120, "stop": 1665056627120, "uuid": "c48ef814-60b3-4993-9c3b-3df75847741c", "historyId": "b26c8bed8934307bd4dc5b023ab68987", "testCaseId": "e0fe90d4c941788db14eaeb3f63e83fb", "fullName": "Rest_api_tests.tests.auth.test_auth.TestAuthUser#test_user_auth_invalid_data", "labels": [{"name": "feature", "value": "test_authorization"}, {"name": "story", "value": "user_auth_invalid_data"}, {"name": "severity", "value": "Normal"}, {"name": "parentSuite", "value": "Rest_api_tests.tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "a668c40338de"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Rest_api_tests.tests.auth.test_auth"}]}