{"name": "test_user_auth_invalid_data", "status": "passed", "steps": [{"name": "Отправляем запрос на аторизацию с неправильными данными", "status": "passed", "start": 1665049283578, "stop": 1665049283578}, {"name": "Проверяем что указанные данные не верны и статус код = 401", "status": "passed", "start": 1665049283578, "stop": 1665049283578}], "start": 1665049283578, "stop": 1665049283578, "uuid": "ee7d1195-b1e0-48ee-b609-eddfc5c3654b", "historyId": "b26c8bed8934307bd4dc5b023ab68987", "testCaseId": "e0fe90d4c941788db14eaeb3f63e83fb", "fullName": "Rest_api_tests.tests.auth.test_auth.TestAuthUser#test_user_auth_invalid_data", "labels": [{"name": "feature", "value": "test_authorization"}, {"name": "severity", "value": "Normal"}, {"name": "story", "value": "user_auth_invalid_data"}, {"name": "parentSuite", "value": "Rest_api_tests.tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "b056829879e1"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Rest_api_tests.tests.auth.test_auth"}]}