{"name": "test_user_auth_invalid_data", "status": "passed", "steps": [{"name": "Отправляем запрос на аторизацию с неправильными данными", "status": "passed", "start": 1665051916551, "stop": 1665051916551}, {"name": "Проверяем что указанные данные не верны и статус код = 401", "status": "passed", "start": 1665051916551, "stop": 1665051916551}], "start": 1665051916551, "stop": 1665051916551, "uuid": "e39c4e7b-54e3-4ab3-ba89-50670f814538", "historyId": "b26c8bed8934307bd4dc5b023ab68987", "testCaseId": "e0fe90d4c941788db14eaeb3f63e83fb", "fullName": "Rest_api_tests.tests.auth.test_auth.TestAuthUser#test_user_auth_invalid_data", "labels": [{"name": "story", "value": "user_auth_invalid_data"}, {"name": "feature", "value": "test_authorization"}, {"name": "severity", "value": "Normal"}, {"name": "parentSuite", "value": "Rest_api_tests.tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "04b7d1b582f1"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Rest_api_tests.tests.auth.test_auth"}]}